# Generated by Django 3.0.2 on 2021-05-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('auther', models.CharField(max_length=100)),
                ('slug', models.CharField(blank=True, max_length=190, null=True, unique=True)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
